name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 1 * * *"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fitzzz/plex-rar2fs:latest

#     - uses: actions/checkout@v2
#     - name: Tag the Docker image
#       run: docker tag plex-rar2fs:$(date +%s) fitzzz/plex-rar2fs:$(date +%s)
    
    - uses: actions/checkout@v2
    - name: Push the Docker image
      run: docker push fitzzz/plex-rar2fs:latest
