name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag plex-rar2fs:$(date +%s)
      run: docker tag plex-rar2fs:$(date +%s) fitzzz/plex-rar2fs:$(date +%s)
      run: docker push fitzzz/plex-rar2fs:latest
docker push new-repo:tagname
