name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Authenticate to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Build the Docker image with lowercase username
      - name: Build Docker image
        run: |
          USERNAME=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/$USERNAME/plex-rar2fs:plexpass
          docker build . --file Dockerfile --tag $IMAGE_NAME

      # Push the Docker image to GHCR
      - name: Push Docker image
        run: |
          USERNAME=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/$USERNAME/plex-rar2fs:plexpass
          docker push $IMAGE_NAME
