name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Logga in i GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Bygg Docker-image
        run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/plex-rar2fs:plexpass

      - name: Pusha Docker-image
        run: docker push ghcr.io/${{ github.repository_owner }}/plex-rar2fs:plexpass
